"#version 410\n"
"uniform mat4 ciModelViewProjection;"
"layout (location=0) in vec3 v_pos;"
"layout (location=1) in float v_rad;"
"layout (location=0) out float g_rad;"
"void main(void)"
"{"
"    gl_Position = ciModelViewProjection * vec4(v_pos, 1);"
"    g_rad = v_rad;"
"}"