"#version 410\n"
"layout (location=0) in vec3 v_min_pos;"
"layout (location=1) in vec3 v_max_pos;"
"layout (location=2) in float v_potential;"
"layout (location=0) out vec3 g_min_pos;"
"layout (location=1) out vec3 g_max_pos;"
"layout (location=2) out float g_potential;"
"void main(void)"
"{"
"    g_min_pos = v_min_pos;"
"    g_max_pos = v_max_pos;"
"    g_potential = v_potential;"
"}"