"#version 410\n"
"#define pi 3.1415926535897932384626433832795\n"
"uniform mat4 ciProjectionMatrix;"
"layout (points) in;"
"layout (triangle_strip, max_vertices = 38) out;"
"layout (location=0) in float g_rad[];"
"void main(void)"
"{"
"    float aspect = ciProjectionMatrix[1][1] / ciProjectionMatrix[0][0];"
"    vec2 scale = vec2(1, aspect) * ciProjectionMatrix[0][0];"
"    float r = g_rad[0];"
"    float n = 20;"
"    gl_Position = gl_in[0].gl_Position + vec4(r*scale.x,0, 0, 0);"
"    EmitVertex();"
"    for (float i = 1; i < n; ++i) {"
"        float t = (i / (n-1)) * 2 * pi;"
"        vec2 xy = r * vec2(cos(t), sin(t));"
"        gl_Position = gl_in[0].gl_Position + vec4(xy.x*scale.x, xy.y*scale.y, 0, 0);"
"        EmitVertex();"
"        gl_Position = gl_in[0].gl_Position;"
"        EmitVertex();"
"    }"
"    EndPrimitive();"
"}"
